### ISSUE TITLE
Configure the theme files in accordance to the theme.

### ISSUE THREAD

**Issue by sahilarora535** [KamandPrompt/kamandprompt.github.io.jekyll#10]
`index.md` needs to be changed to `index.html` and other changes need to be made in accordance to the theme. See the 'Starting from Jekyll New' section here: <https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/>

**Comment by Varunvaruns9** [comment]
Sorry, referenced the wrong issue. Corrected in the commit and pr.

**Comment by Varunvaruns9** [comment]
Should I keep the Intro to jekyll post or delete it?
about.md in root should be deleted or shifted to _pages?
