### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by sahilarora535** [KamandPrompt/kamandprompt.github.io.jekyll#5]
A license is an important part of any open-source project, and hence need to be added here as well.

The MIT License should be good here. See here for more help on the topic: <https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project>

**Comment by unkemptArc99** [comment]
Please see https://github.com/KamandPrompt/kamandprompt.github.io/pull/17
