### ISSUE TITLE
Update navigation links on website header

### ISSUE THREAD

**Issue by sahilarora535** [KamandPrompt/kamandprompt.github.io.jekyll#6]
The navigation links on the header need to be updated as per requirements. The instructions can be found here: <https://mmistakes.github.io/minimal-mistakes/docs/navigation/>

**Comment by rishi-s8** [comment]
I have added the titles to navigation links as per the old website, but what should be the URLs to the navigation links?

**Comment by sahilarora535** [comment]
@rishi-s8  we can set the navigation links later. We just need to add the pages and the links will be active.
