### ISSUE TITLE
_config.yml: Configure site settings for the website.

### ISSUE THREAD

**Issue by sahilarora535** [KamandPrompt/kamandprompt.github.io.jekyll#7]
The `_config.yml` file needs to be set up for the website. The instructions can be found here: <https://mmistakes.github.io/minimal-mistakes/docs/configuration/>

**Comment by akshat157** [comment]
Is the file to be modified just for the initial setup now? What all will be included is yet to be decided I believe. If not, you can mention some of the features here so that I add the requisites accordingly.

**Comment by sahilarora535** [comment]
Yeah it is difficult to add all the configuration settings right now. I think the `contrast` theme should be good. WDYT?

Rest you fill whatever you can, such as social links like kamand prompt group.. and programming club page on facebook, email ID, site_search. Skip the comments for now. Rest we can see what all needs to be configured.

**Comment by akshat157** [comment]
`contrast` skin seems fine. How about `Dark` though? Its colors match with that of the pre-built UI.

**Comment by sahilarora535** [comment]
If that looks good to you, I have no issues. Anyways, we can change it easily. 😃
